FROM node:22-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ARG VITE_BASE_URL
ARG VITE_BACKEND_ROOT_URL
ARG VITE_GEONODE_REST_URL
ARG VITE_GEOSERVER_ROOT_URL
ARG VITE_GEOSERVER_BASE_URL
ARG VITE_MAPTILER_API_KEY
ARG VITE_INHOUSE_MAP_BASE_URL
ARG VITE_INHOUSE_MAP_API_KEY
ARG VITE_MAP_START_LNG
ARG VITE_MAP_START_LAT
ARG VITE_MAP_START_ZOOM

ENV VITE_BASE_URL=$VITE_BASE_URL
ENV VITE_BACKEND_ROOT_URL=$VITE_BACKEND_ROOT_URL
ENV VITE_GEONODE_REST_URL=$VITE_GEONODE_REST_URL
ENV VITE_GEOSERVER_ROOT_URL=$VITE_GEOSERVER_ROOT_URL
ENV VITE_GEOSERVER_BASE_URL=$VITE_GEOSERVER_BASE_URL
ENV VITE_MAPTILER_API_KEY=$VITE_MAPTILER_API_KEY
ENV VITE_INHOUSE_MAP_BASE_URL=$VITE_INHOUSE_MAP_BASE_URL
ENV VITE_INHOUSE_MAP_API_KEY=$VITE_INHOUSE_MAP_API_KEY
ENV VITE_MAP_START_LNG=$VITE_MAP_START_LNG
ENV VITE_MAP_START_LAT=$VITE_MAP_START_LAT
ENV VITE_MAP_START_ZOOM=$VITE_MAP_START_ZOOM

RUN npm run build

FROM nginx:1.27-alpine AS production

COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD wget -q -O - http://127.0.0.1/healthz || exit 1

CMD ["nginx", "-g", "daemon off;"]
